version: '3.8'

services:
  todo-app:
    build: ./
    command: ./wait-for-postgres.sh db ./todo-app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./docker/postgres/postgres:/var/lib/postgresql
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432


volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local